/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testApp;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String agrs[])
    {
    	String names="Vijay";
    	System.out.println(names);
    }
}
